name: Build LaTeX documents
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        document: ['main']
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Inject environment variables
        run: |
          sed -i env.tex -e "s/GITHUBCOMMITHASH/${GITHUB_SHA:0:6}/g"
          sed -i env.tex -e "s/GITHUBRUNNUMBER/${GITHUB_RUN_ID}/g"
          cat env.tex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ matrix.document }}.tex
      - name: Move to deploy directory
        run: |
          mv ${{ matrix.document }}.pdf deploy/${{ matrix.document }}.pdf
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.document }}
          path: deploy/
  deploy_website:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Download documents
        uses: actions/download-artifact@v2
        with:
          path: deploy/
      - name: List documents
        run: ls -R
        working-directory: deploy
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: github.event_name == 'push'
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: deploy # The folder the action should deploy.
